############################
## CHANGE THESE
############################

baseURL: "https://KamilPietrzak.github.io/Blog-test"
title: Blog-test

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
